generate:
  models: true
  std-http-server: true
  strict-server: true
  embedded-spec: true
output-options:
  name-normalizer: ToCamelCaseWithInitialisms
  overlay:
    path: ./overlay.yml
    strict: false
